data_2019_Q1 <- read.csv('/Users/anna/Desktop/Case Study Cyclistic/2019 data/Divvy_Trips_2019_Q1.csv')
data_2019_Q2 <- read.csv('/Users/anna/Desktop/Case Study Cyclistic/2019 data/Divvy_Trips_2019_Q2.csv')
data_2019_Q3 <- read.csv('/Users/anna/Desktop/Case Study Cyclistic/2019 data/Divvy_Trips_2019_Q3.csv')
data_2019_Q4 <- read.csv('/Users/anna/Desktop/Case Study Cyclistic/2019 data/Divvy_Trips_2019_Q4.csv')
library(dplyr)
library(lubridate)
head(data_2019_Q1)
#data_2019_Q1_PRO <- data_2019_Q1 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = weekdays(as.Date(start_time)))
data_2019_Q1_PRO <- data_2019_Q1 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = lubridate::wday(start_time, week_start = 1))
head(data_2019_Q1_PRO)

head(data_2019_Q2)
#data_2019_Q2_PRO <- data_2019_Q2 %>% mutate(ride_length = hms::as_hms(difftime(X01...Rental.Details.Local.End.Time, X01...Rental.Details.Local.Start.Time)), day_of_week = weekdays(as.Date(X01...Rental.Details.Local.Start.Time)))
data_2019_Q2_PRO <- data_2019_Q2 %>% mutate(ride_length = hms::as_hms(difftime(X01...Rental.Details.Local.End.Time, X01...Rental.Details.Local.Start.Time)), day_of_week = lubridate::wday(X01...Rental.Details.Local.Start.Time, week_start = 1))
head(data_2019_Q2_PRO)

head(data_2019_Q3)
#data_2019_Q3_PRO <- data_2019_Q3 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = weekdays(as.Date(start_time)))
data_2019_Q3_PRO <- data_2019_Q3 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = lubridate::wday(start_time, week_start = 1))
head(data_2019_Q3_PRO)

head(data_2019_Q4)
#data_2019_Q4_PRO <- data_2019_Q4 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = weekdays(as.Date(start_time)))
data_2019_Q4_PRO <- data_2019_Q4 %>% mutate(ride_length = hms::as_hms(difftime(end_time, start_time)), day_of_week = lubridate::wday(start_time, week_start = 1))
head(data_2019_Q4_PRO)
